ARG BASE="rust:1.75-bullseye"
ARG RUNTIME="debian:bullseye-slim"
ARG WORK_DIR="/rs-relay"

FROM ${BASE} as tester
ARG WORK_DIR

# Configure system dependencies.
RUN apt update && \
  apt install -y  --no-install-recommends \
  gcc musl-dev musl-tools protobuf-compiler clang

WORKDIR ${WORK_DIR}
COPY . .
