{
 "title": "IRN",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "selected_node",
    "query": {
     "query": "label_values(irn_cpu_usage_percent_per_core_gauge,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avg CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(irn_cpu_usage_percent_per_core_gauge) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Max CPU load (core)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(irn_cpu_usage_percent_per_core_gauge) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Min CPU load (core)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "min(irn_cpu_usage_percent_per_core_gauge) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irn_used_memory / irn_total_memory * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Available RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "irn_available_memory", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Total RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "irn_total_memory", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - irn_disk_available_space / irn_disk_total_space) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Available disk space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "irn_disk_available_space", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Total disk space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "irn_disk_total_space", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Network tx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(irn_network_tx_bytes_total[1m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Network rx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(irn_network_rx_bytes_total[1m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Inbound RPC/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(futures_started_count{future_name=\"inbound_rpc\"}[1m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Outbound RPC/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(futures_started_count{future_name=\"outbound_rpc\"}[1m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Inbound RPC/s (per selected node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(futures_started_count{future_name=\"inbound_rpc\", job = \"$selected_node\"}[1m])) by (rpc_name)",
     "legendFormat": "{{rpc_name}}"
    }
   ]
  },
  {
   "title": "Outbound RPC/s (per selected node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(futures_started_count{future_name=\"outbound_rpc\", job = \"$selected_node\"}[1m])) by (rpc_name)",
     "legendFormat": "{{rpc_name}}"
    }
   ]
  },
  {
   "title": "Inbound RPC duration (per selected node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(future_duration_sum{future_name=\"inbound_rpc\", job = \"$selected_node\", rpc_kind != \"streaming\"}[1m]) / rate(future_duration_count{future_name=\"inbound_rpc\", job = \"$selected_node\", rpc_kind != \"streaming\"}[1m])",
     "legendFormat": "{{rpc_name}}"
    }
   ]
  },
  {
   "title": "Outbound RPC duration (per selected node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(future_duration_sum{future_name=\"outbound_rpc\", job = \"$selected_node\", rpc_kind != \"streaming\"}[1m]) / rate(future_duration_count{future_name=\"outbound_rpc\", job = \"$selected_node\", rpc_kind != \"streaming\"}[1m])",
     "legendFormat": "{{rpc_name}}"
    }
   ]
  },
  {
   "title": "Inbound streaming RPC duration (per selected node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(future_duration_sum{future_name=\"inbound_rpc\", job = \"$selected_node\", rpc_kind = \"streaming\"}[1m]) / rate(future_duration_count{future_name=\"inbound_rpc\", job = \"$selected_node\", rpc_kind = \"streaming\"}[1m])",
     "legendFormat": "{{rpc_name}}"
    }
   ]
  },
  {
   "title": "Outbound streaming RPC duration (per selected node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(future_duration_sum{future_name=\"outbound_rpc\", job = \"$selected_node\", rpc_kind = \"streaming\"}[1m]) / rate(future_duration_count{future_name=\"outbound_rpc\", job = \"$selected_node\", rpc_kind = \"streaming\"}[1m])",
     "legendFormat": "{{rpc_name}}"
    }
   ]
  },
  {
   "title": "Storage operation duration (per selected node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(future_duration_total{future_name = \"storage_operation\"}[1m]) / rate(future_duration_count{future_name = \"storage_operation\"}[1m])) by(op_name)",
     "legendFormat": "{{op_name}}"
    }
   ]
  },
  {
   "title": "Future poll duration (per selected node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "future_poll_duration_max",
     "legendFormat": "{{future_name}} {{rpc_name}}{{op_name}}"
    }
   ]
  }
 ]
}